name: filebeat
setup.template:
  enabled: true
setup.kibana:
  host: "https://kibana:5601"
  ssl.enabled: true
  ssl.certificate_authorities: [ "${CONFIG_DIR}/ca.crt" ]
  ssl.certificate: "${CONFIG_DIR}/filebeat.crt"
  ssl.key: "${CONFIG_DIR}/filebeat.key"
output.elasticsearch.username: ${ELASTIC_USERNAME}
output.elasticsearch.password: ${ELASTIC_PASSWORD}
path.config: ${CONFIG_DIR}

processors:
  - add_cloud_metadata: ~

filebeat.config:
  modules:
    path: ${path.config}/modules.d/*.yml
    reload.enabled: false

filebeat.inputs:
  - type: tcp
    enabled: true
    max_message_size: 10MiB
    host: "https://filebeat:9000"

filebeat.autodiscover:
  providers:
    # The Docker autodiscover provider automatically retrieves logs from Docker
    # containers as they start and stop.
    - type: docker
      hints.enabled: true

monitoring:
  enabled: true
  elasticsearch:
    hosts: ["https://elasticsearch:9200"]
    ssl.certificate_authorities: [ "${CONFIG_DIR}/ca.crt" ]
    ssl.certificate: "${CONFIG_DIR}/filebeat.crt"
    ssl.key: "${CONFIG_DIR}/filebeat.key"

output.logstash:
  enabled: true
  hosts: ["https://logstash:5044"]
  username: filebeat_internal
  password: '${FILEBEAT_INTERNAL_PASSWORD}'
  ssl.certificate_authorities: ["${CONFIG_DIR}/ca.crt"]
  ssl.certificate: "${CONFIG_DIR}/filebeat.crt"
  ssl.key: "${CONFIG_DIR}/filebeat.key"

output.elasticsearch:
  enabled: true
  hosts: ["https://elasticsearch:9200"]
  ssl.certificate_authorities: ["${CONFIG_DIR}/ca.crt"]
  ssl.certificate: "${CONFIG_DIR}/filebeat.crt"
  ssl.key: "${CONFIG_DIR}/filebeat.key"

http:
  enabled: true
  host: 0.0.0.0

# filebeat.modules:
