version: "3.8"

services:
  ###   MONITORING   ###

  grafana:
    image: grafana/grafana:10.2.0
    container_name: grafana
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /home/sinless777/services/helix/grafana/grafana.ini:/etc/grafana/grafana.ini
      - /home/sinless777/services/helix/grafana/provisioning/:/etc/grafana/provisioning
      - /home/sinless777/services/helix/grafana/dashboards/:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"

  prometheus:
    image: prom/prometheus:v2.26.0
    container_name: prometheus
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /home/sinless777/services/helix/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - 9090:9090
    command: --web.enable-lifecycle  --config.file=/etc/prometheus/prometheus.yml

  node-exporter:
    image: prom/node-exporter
    container_name: node-exporter
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - --collector.filesystem.ignored-mount-points
      - "^/(sys|proc|dev|host|etc|rootfs/var/lib/docker/containers|rootfs/var/lib/docker/overlay2|rootfs/run/docker/netns|rootfs/var/lib/docker/aufs)($$|/)"
    ports:
      - 9100:9100

  ###   SONAR   ###

  sonarqube:
    image: sonarqube:community
    container_name: sonarqube
    hostname: sonarqube
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "9900:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://pg:5432/sonar
    depends_on:
      - pg

  pg:
    image: postgres:13.2
    container_name: pg
    hostname: pg
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "5432:5432"
    volumes:
      - /home/sinless777/services/helix/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar

