version: "3.8"

secrets:
  ca.crt:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificate_authority/ca/ca.crt

  elastic-stack-ca.p12:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificate_authority/elastic-stack-ca.p12

  filebeat.key:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/filebeat/filebeat.key

  filebeat.cert:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/filebeat/filebeat.crt

  metricbeat.key:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/metricbeat/metricbeat.key

  metricbeat.cert:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/metricbeat/metricbeat.crt

  packetbeat.key:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/packetbeat/packetbeat.key

  packetbeat.cert:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/packetbeat/packetbeat.crt

################
##  NETWORKS  ##
################
networks:
  elastic-net:
    name: elastic-net
    external: true

  proxy-net:
    external: true

  weave-net:
    external: true

services:

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:${ELK_VERSION}
    container_name: packetbeat
    hostname: packetbeat
    user: "root"
    networks:
      - elastic-net
      - weave-net
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: packetbeat -e -strict.perms=false
    volumes:
      - ${PACKETBEAT_DIR}/config/data:/usr/share/packetbeat/data
      - ${SECRETS_DIR}/elastic_stack/packetbeat/config/packetbeat.yml:${PACKETBEAT_DIR}/packetbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONFIG_DIR: ${PACKETBEAT_DIR}/config
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LS_JAVA_OPTS: "-Xmx${PACKETBEAT_HEAP} -Xms${PACKETBEAT_HEAP}"
    secrets:
      - source: ca.crt
        target: ${PACKETBEAT_DIR}/config/ca.crt
      - source: packetbeat.cert
        target: ${PACKETBEAT_DIR}/config/packetbeat.cert
      - source: packetbeat.key
        target: ${PACKETBEAT_DIR}/config/packetbeat.key
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    deploy:
      mode: global

  metricbeat:
    container_name: metricbeat
    hostname: metricbeat
    user: root #/var/run/docker.sock
    image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    entrypoint: [ ]
    command: >
      bash -c '
        metricbeat -e \
          -E setup.kibana.enabled=true \
          -E setup.kibana.host=http://kibana:5601 \
          -E setup.template.enabled=true \
          -E setup.template.settings.index.number_of_replicas=0 \
          -E http.enabled=true \
          -E http.host=0.0.0.0 \
          -E http.port=5066 \
          -E monitoring.enabled=false \
          -E output.elasticsearch.username=elastic \
          -E output.elasticsearch.password=$ELASTIC__INITIAL_PASSWORD \
          -E output.elasticsearch.hosts=["http://elasticsearch:9200"] \
          -E monitoring.cluster_uuid=$(cat /usr/share/setup/cluster_uuid) \
        '
    volumes:
      - ${SECRETS_DIR}/elastic_stack/metricbeat/config/metricbeat.yml:${METRICBEAT_DIR}/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONFIG_DIR: ${METRICBEAT_DIR}/config
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LS_JAVA_OPTS: "-Xmx${METRICBEAT_HEAP} -Xms${METRICBEAT_HEAP}"
    secrets:
      - source: elastic-stack-ca.p12
        target: /etc/pki/ca-trust/source/anchors/elastic-stack-ca.p12
      - source: ca.crt
        target: /etc/pki/ca-trust/source/anchors/ca.crt
      - source: metricbeat.cert
        target: ${METRICBEAT_DIR}/config/metricbeat.crt
      - source: metricbeat.key
        target: ${METRICBEAT_DIR}/config/metricbeat.key
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      co.elastic.logs/enabled: false
      co.elastic.metrics/raw: "[{\"module\":\"beat\",\"hosts\":\"metricbeat:5066\",\"period\":\"10s\",\"xpack.enabled\":\"true\"}]"
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5066/

  filebeat:
    container_name: filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    restart: unless-stopped
    user: root #/var/run/docker.sock
    entrypoint: [ ]
    command: >
      bash -c '
        filebeat -e \
          -E setup.kibana.enabled=true \
          -E setup.kibana.host=http://kibana:5601 \
          -E setup.template.enabled=true \
          -E setup.template.settings.index.number_of_replicas=0 \
          -E http.enabled=true \
          -E http.host=0.0.0.0 \
          -E http.port=5066 \
          -E monitoring.enabled=false \
          -E output.elasticsearch.username=elastic \
          -E output.elasticsearch.password=$ELASTIC__INITIAL_PASSWORD \
          -E output.elasticsearch.hosts=["http://elasticsearch:9200"] \
          -E monitoring.cluster_uuid=$(cat /usr/share/setup/cluster_uuid) \
      '
    volumes:
      - ${SECRETS_DIR}/elastic_stack/filebeat/config/filebeat.yml:${FILEBEAT_DIR}/filebeat.yml:ro
    environment:
      CONFIG_DIR: ${FILEBEAT_DIR}/config
      LS_JAVA_OPTS: "-Xmx${FILEBEAT_HEAP} -Xms${FILEBEAT_HEAP}"
    secrets:
      - source: ca.crt
        target: ${FILEBEAT_DIR}/config/ca.crt
      - source: filebeat.cert
        target: ${FILEBEAT_DIR}/config/filebeat.crt
      - source: filebeat.key
        target: ${FILEBEAT_DIR}/config/filebeat.key
    expose:
      - 9000
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
      co.elastic.logs/enabled: false
      co.elastic.metrics/raw: "[{\"module\":\"beat\",\"hosts\":\"filebeat:5066\",\"period\":\"10s\",\"xpack.enabled\":\"true\"}]"
    healthcheck:
      interval: 10s
      retries: 12
      test: curl --write-out 'HTTP %{http_code}' --fail --silent --output /dev/null http://localhost:5066/
