version: "3.9"

################
##  Networks  ##
################
networks:
  proxy-net:
    external: true

services:
  ################
  ##  Websites  ##
  ################

  sinlessgames:
    image: sinless777/gateway:1.1.3
    restart: always
    networks:
      - proxy-net
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      replicas: 3

  mobius:
    image: sinless777/mobius_gateway:latest
    restart: always
    networks:
      - proxy-net
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      replicas: 3