version: "3.9"

###############
##  Volumes  ##
###############
volumes:
  heimdall:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/heimdall
      o: bind

################
##  NETWORKS  ##
################
networks:
  devops-net:
    driver: overlay

  proxy-net:
    external: true
    driver: overlay

  weave-net:
    external: true
    driver: overlay

services:
  heimdall:
    image: linuxserver/heimdall
    privileged: true
    networks:
      - proxy-net
      - devops-net
      - weave-net
    ports:
      - "3443:443"
      - "3081:80"
    volumes:
      - heimdall:/config
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.25'
          memory: 256M
    labels:
      com.centurylinklabs.watchtower.enable: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3443"]
      interval: 30s
      timeout: 5s
      retries: 5
