version: "3.9"

################
##  Networks  ##
################
networks:
  proxy-net:
    external: true

  weave-net:
    external: true

services:
  ################
  ##  Websites  ##
  ################

  sinlessgames:
    image: sinless777/gateway:1.1.3
    restart: always
    networks:
      - proxy-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      replicas: 3
    healthcheck:
      test: ["CMD", "curl", "-f", "https://sinlessgamesllc.com"]
      interval: 10s
      timeout: 10s
      retries: 5

  mobius:
    image: sinless777/mobius_gateway:latest
    restart: always
    networks:
      - proxy-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      replicas: 3
    healthcheck:
        test: ["CMD", "curl", "-f", "https://mobiusinferniummc.com"]
        interval: 10s
        timeout: 10s
        retries: 5