version: "3.9"

################
##  Networks  ##
################
networks:
  home-net:
    driver: overlay

  weave-net:
    driver: overlay

  proxy-net:
    driver: overlay

###############
##  Volumes  ##
###############
volumes:
  portainer_data:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /home/sinless777/services/portainer_data

services:
  portainer:
    image: portainer/portainer-ce:latest
    security_opt:
      - no-new-privileges:true
    networks:
      - weave-net
      - proxy-net
      - home-net
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager, node.labels.cicdBuildsOnly != true]
      update_config:
        parallelism: 1
      restart_policy:
        condition: any
      labels:
        - com.centurylinklabs.watchtower.enable=true
        - portainer_service
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

  agent:
    image: portainer/agent
    environment:
      AGENT_CLUSTER_ADDR: tasks.agent
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - weave-net
      - proxy-net
      - home-net
    deploy:
      mode: global
      placement:
        constraints: [node.platform.os == linux]
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - com.centurylinklabs.watchtower.enable=true

  watchtower:
    image: containrrr/watchtower
    restart: always
    networks:
      - weave-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 6 * * *
    deploy:
      mode: replicated
      replicas: 1
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
        reservations:
          cpus: '0.25'
          memory: 128M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - com.centurylinklabs.watchtower.enable=true

  weavescope:
    image: weaveworks/scope:latest
    hostname: weavescope
    pid: "host"
    privileged: true
    restart: always
    networks:
      - weave-net
    ports:
      - "4040:4040"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
      - "--weave=false"
    deploy:
      mode: global
      resources:
        limits:
          cpus: '1.0'
          memory: 512M
        reservations:
          cpus: '0.5'
          memory: 256M
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4040"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    labels:
      - works.weave.role=system
      - com.centurylinklabs.watchtower.enable=true
