version: "3.8"

secrets:
  ca.crt:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificate_authority/ca/ca.crt

  elastic-stack-ca.p12:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificate_authority/elastic-stack-ca.p12

  filebeat.key:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/filebeat/filebeat.key

  filebeat.cert:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/filebeat/filebeat.crt

  metricbeat.key:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/metricbeat/metricbeat.key

  metricbeat.cert:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/metricbeat/metricbeat.crt

  packetbeat.key:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/packetbeat/packetbeat.key

  packetbeat.cert:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/packetbeat/packetbeat.crt

################
##  NETWORKS  ##
################
networks:
  elastic-net:
    external: true

  proxy-net:
    external: true

  weave-net:
    external: true

services:
  packetbeat:
    container_name: packetbeat
    hostname: packetbeat
    user: root
    image: docker.elastic.co/beats/packetbeat:${ELK_VERSION}
    restart: unless-stopped
    profiles:
      - monitoring
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: packetbeat -e -strict.perms=false
    volumes:
      - ${SECRETS_DIR}/elastic_stack/packetbeat/config/packetbeat.yml:${PACKETBEAT_DIR}/packetbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONFIG_DIR: ${PACKETBEAT_DIR}/config
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LS_JAVA_OPTS: "-Xmx${PACKETBEAT_HEAP} -Xms${PACKETBEAT_HEAP}"
    secrets:
      - source: ca.crt
        target: ${PACKETBEAT_DIR}/config/ca.crt
      - source: packetbeat.cert
        target: ${PACKETBEAT_DIR}/config/packetbeat.crt
      - source: packetbeat.key
        target: ${PACKETBEAT_DIR}/config/packetbeat.key
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  metricbeat:
    container_name: metricbeat
    hostname: metricbeat
    user: root
    image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
    restart: unless-stopped
    profiles:
      - monitoring
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: "/bin/bash -c while true; do metricbeat -e; sleep 1; done"
    volumes:
      - ${SECRETS_DIR}/elastic_stack/metricbeat/config/metricbeat.yml:${METRICBEAT_DIR}/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONFIG_DIR: ${METRICBEAT_DIR}/config
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LS_JAVA_OPTS: "-Xmx${METRICBEAT_HEAP} -Xms${METRICBEAT_HEAP}"
    secrets:
      - source: elastic-stack-ca.p12
        target: /etc/pki/ca-trust/source/anchors/elastic-stack-ca.p12
      - source: ca.crt
        target: /etc/pki/ca-trust/source/anchors/ca.crt
      - source: metricbeat.cert
        target: ${METRICBEAT_DIR}/config/metricbeat.crt
      - source: metricbeat.key
        target: ${METRICBEAT_DIR}/config/metricbeat.key
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"

  filebeat:
    container_name: filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    restart: unless-stopped
    command: filebeat -e -strict.perms=false
    profiles:
      - monitoring
    volumes:
      - ${SECRETS_DIR}/elastic_stack/filebeat/config/filebeat.yml:${FILEBEAT_DIR}/filebeat.yml:ro
    environment:
      CONFIG_DIR: ${FILEBEAT_DIR}/config
      LS_JAVA_OPTS: "-Xmx${FILEBEAT_HEAP} -Xms${FILEBEAT_HEAP}"
    secrets:
      - source: ca.crt
        target: ${FILEBEAT_DIR}/config/ca.crt
      - source: filebeat.cert
        target: ${FILEBEAT_DIR}/config/filebeat.crt
      - source: filebeat.key
        target: ${FILEBEAT_DIR}/config/filebeat.key
    expose:
      - 9000
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
