version: "3.9"

###############
##  Volumes  ##
###############
volumes:
  jenkins:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/jenkins
      o: bind

  heimdall:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/heimdall
      o: bind

################
##  NETWORKS  ##
################
networks:
  devops-net:
    name: devops-net
    driver: bridge

  proxy-net:
    external: true

  weave-net:
    external: true

services:

  mysql:
    image: mysql:8.2
    volumes:
      - /home/sinless777/services/mysql/helix:/var/lib/mysql
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}


  ####################
  ##  DevOps Stack  ##
  ####################

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    privileged: true
    user: root
    networks:
      - devops-net
      - proxy-net
      - weave-net
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s -o /dev/null https://jenkins.sinlessgamesllc.com/ || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5

  github-runner:
    image: sinless777/github-action-runner
    restart: always
    networks:
      - devops-net
      - weave-net
    environment:
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      ORGANIZATION: ${ORGANIZATION}

  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: always
    privileged: true
    networks:
      - proxy-net
      - devops-net
      - weave-net
    ports:
      - "3443:443"
      - "3081:80"
    volumes:
      - heimdall:/config
    labels:
      com.centurylinklabs.watchtower.enable: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3443"]
      interval: 1s
      timeout: 5s
      retries: 5
