version: "3.9"

################
##  Networks  ##
################
networks:
  home-net:
    external: true

  weave-net:
    external: true

  proxy-net:
    name: proxy-net
    driver: bridge

###############
##  Volumes  ##
###############
volumes:
  unifi:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/unifi
      o: bind

  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/mysql/nginx-proxy
      o: bind

  nginx_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/nginx-proxy
      o: bind

  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/letsencrypt
      o: bind

services:
  ##########################################
  ##  Network Load Balancer for Services  ##
  ##########################################
  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: always
    container_name: nginx-proxy
    networks:
      - home-net
      - proxy-net
      - weave-net
    ports:
      # These ports are in format <host-port>:<container-port>
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
      # Add any other Stream port you want to expose
      - '21:21' # FTP
    environment:
      # Mysql/Maria connection parameters:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: "npm"
      DB_MYSQL_PASSWORD: "npm"
      DB_MYSQL_NAME: "npm"
      # Uncomment this if IPv6 is not enabled on your host
      # DISABLE_IPV6: 'true'
    volumes:
      - nginx_data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    labels:
      com.centurylinklabs.watchtower.enable: true
    healthcheck:
      test: [ "CMD", "/bin/check-health" ]
      interval: 10s
      timeout: 3s

  db:
    image: 'jc21/mariadb-aria:latest'
    restart: always
    container_name: nginx-proxy-db
    networks:
      - proxy-net
      - weave-net
    environment:
      MYSQL_ROOT_PASSWORD: 'npm'
      MYSQL_DATABASE: 'npm'
      MYSQL_USER: 'npm'
      MYSQL_PASSWORD: 'npm'
    volumes:
      - mysql_data:/var/lib/mysql
    labels:
      com.centurylinklabs.watchtower.enable: true

  ##########################
  ##  Network Controller  ##
  ##########################

  unifi:
    image: lscr.io/linuxserver/unifi-network-application:latest # lscr.io/linuxserver/unifi-controller:latest
    restart: always
    container_name: unifi
    depends_on:
      - unifi-db
    networks:
      - home-net
      - weave-net
      - proxy-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - MEM_LIMIT=4096 #optional
      - MEM_STARTUP=1024 #optional
      - MONGO_USER=unifi
      - MONGO_PASS=pass
      - MONGO_HOST=unifi-db
      - MONGO_PORT=27017
      - MONGO_DBNAME=unifi
    volumes:
      - unifi:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    labels:
      com.centurylinklabs.watchtower.enable: true

  unifi-db:
      image: mongo:7.0.2-nanoserver-1809
      container_name: unifi-db
      networks:
        - home-net
        - weave-net
        - proxy-net
      ports:
        - 127.0.0.1:27017:27017
      environment:
        # - ALLOW_EMPTY_PASSWORD=yes
        - MONGODB_ENABLE_DIRECTORY_PER_DB=yes
        # - MONGODB_INITDB_DATABASE=unifi
        - MONGODB_INITDB_ROOT_USERNAME=unifi
        - MONGODB_INITDB_ROOT_PASSWORD=pass
        # - MONGODB_USERNAME=unifi
        # - MONGODB_PASSWORD=pass
      volumes:
        - type: bind
          source: ./data
          target: /home/sinless777/services/unifi/mongo
      labels:
        com.centurylinklabs.watchtower.enable: true

  ################
  ##  Websites  ##
  ################

  sinlessgames:
    image: sinless777/gateway:1.1.3
    restart: always
    networks:
      - proxy-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      replicas: 3

  mobius:
    image: sinless777/mobius_gateway:latest
    restart: always
    networks:
      - proxy-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      replicas: 3
