version: "3.9"

###############
##  Volumes  ##
###############
volumes:
  jenkins:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/jenkins
      o: bind

  heimdall:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/heimdall
      o: bind

################
##  NETWORKS  ##
################
networks:
  devops-net:
    name: devops-net
    driver: bridge

  proxy-net:
    external: true

  weave-net:
    external: true

services:
  ####################
  ##  DevOps Stack  ##
  ####################

  jenkins:
    image: jenkins/jenkins:lts
    restart: always
    container_name: jenkins
    privileged: true
    user: root
    networks:
      - devops-net
      - proxy-net
      - weave-net
    volumes:
      - jenkins:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      com.centurylinklabs.watchtower.enable: true
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s -o /dev/null https://jenkins.sinlessgamesllc.com/ || exit 1"]
      interval: 30s
      interval: 10s
      retries: 5


  jenkins-agent-1:
      image: jenkins/ssh-agent:jdk11
      privileged: true
      container_name: jenkins-agent-1
      networks:
          - devops-net
          - weave-net
      user: root
      expose:
        - 22
      environment:
        - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOeItPaeqU5tYtbBtrPRLTX9J2nkFXHVosUSPFLZ0fps disdainful777@gmail.com

  jenkins-agent-2:
      image: jenkins/ssh-agent:jdk11
      privileged: true
      container_name: jenkins-agent-2
      networks:
          - devops-net
          - weave-net
      user: root
      expose:
        - 22
      environment:
        - JENKINS_AGENT_SSH_PUBKEY=ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOeItPaeqU5tYtbBtrPRLTX9J2nkFXHVosUSPFLZ0fps disdainful777@gmail.com
  heimdall:
    image: linuxserver/heimdall
    container_name: heimdall
    restart: always
    privileged: true
    networks:
      - proxy-net
      - devops-net
      - weave-net
    ports:
      - "3443:443"
      - "3081:80"
    volumes:
      - heimdall:/config
    labels:
      com.centurylinklabs.watchtower.enable: true
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3443"]
      interval: 1s
      timeout: 5s
      retries: 5
