version: "3.8"

secrets:
  ca.crt:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificate_authority/ca/ca.crt

  elastic-stack-ca.p12:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificate_authority/elastic-stack-ca.p12

  filebeat.key:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/filebeat/filebeat.key

  filebeat.cert:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/filebeat/filebeat.crt

  metricbeat.key:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/metricbeat/metricbeat.key

  metricbeat.cert:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/metricbeat/metricbeat.crt



################
##  NETWORKS  ##
################
networks:
  elastic-net:
    name: elastic-net
    external: true

  proxy-net:
    external: true

  weave-net:
    external: true

services:

  packetbeat:
    image: docker.elastic.co/beats/packetbeat:${ELK_VERSION}
    container_name: packetbeat
    hostname: packetbeat
    user: "root"
    networks:
      - elastic-net
      - weave-net
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command:
      # Log to stderr.
      - -e
      # Disable config file permissions checks. Allows mounting
      # 'config/filebeat.yml' even if it's not owned by root.
      # see: https://www.elastic.co/guide/en/beats/libbeat/current/config-file-permissions.html
      - --strict.perms=false
    volumes:
      - ${PACKETBEAT_DIR}/data:/usr/share/packetbeat/data
      - ${SECRETS_DIR}/elastic_stack/packetbeat/config/packetbeat.yml:${PACKETBEAT_DIR}/packetbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONFIG_DIR: ${PACKETBEAT_DIR}/config
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LS_JAVA_OPTS: "-Xmx${PACKETBEAT_HEAP} -Xms${PACKETBEAT_HEAP}"
    secrets:
      - source: ca.crt
        target: /etc/pki/ca-trust/source/anchors/ca.crt
      - source: packetbeat.cert
        target: /etc/pki/tls/certs/packetbeat.crt
      - source: packetbeat.key
        target: /etc/pki/tls/private/packetbeat.key
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    links:
      - logstash
    deploy:
      mode: global

