version: "3.9"

################
##  NETWORKS  ##
################
networks:
  helix-ai-net:
    external: true

  proxy-net:
    external: true

  weave-net:
    external: true

###############
##  Volumes  ##
###############

volumes:
  mysql_data1:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/helix/mysql
      o: bind

services:
  #################################
  ###                           ###
  ###       Helix Ai Stack      ###
  ###                           ###
  #################################

  ###   CONSUL   ###

  consul-server1:
    image: hashicorp/consul:1.17.2
    container_name: consul-server1
    hostname: consul-server1
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - vault-server
    restart: always
    volumes:
      - /home/sinless777/services/helix/consul/server1.json:/consul/config/server1.json
      - /home/sinless777/services/helix/certs/:/consul/config/certs/:ro
      - /home/sinless777/services/helix/consul/acls/:/consul/config/acls/
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=3"

  consul-server2:
    image: hashicorp/consul:1.17.2
    container_name: consul-server2
    hostname: consul-server2
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - vault-server
    restart: always
    volumes:
      - /home/sinless777/services/helix/consul/server2.json:/consul/config/server2.json
      - /home/sinless777/services/helix/certs/:/consul/config/certs/:ro
      - /home/sinless777/services/helix/consul/acls/:/consul/config/acls/
    command: "agent -bootstrap-expect=3"

  consul-server3:
    image: hashicorp/consul:1.17.2
    container_name: consul-server3
    hostname: consul-server3
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    depends_on:
      - vault-server
    volumes:
      - /home/sinless777/services/helix/consul/server3.json:/consul/config/server3.json
      - /home/sinless777/services/helix/certs/:/consul/config/certs/:ro
      - /home/sinless777/services/helix/consul/acls/:/consul/config/acls/
    command: "agent -bootstrap-expect=3"

  consul-client:
    image: hashicorp/consul:1.17.2
    container_name: consul-client
    hostname: consul-client
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - /home/sinless777/services/helix/consul/client.json:/consul/config/client.json
      - /home/sinless777/services/helix/certs/:/consul/config/certs/:ro
      - /home/sinless777/services/helix/tokens/:/consul/config/tokens/
    command: "agent"

  ###   VAULT   ###

  vault-server:
    image: hashicorp/vault:1.15.4
    container_name: vault-server
    hostname: vault-server
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: "http://vault-server:8200"
      VAULT_API_ADDR: "http://vault-server:8200"
      VAULT_DEV_ROOT_TOKEN_ID: "vault-plaintext-root-token"
      CONSUL_HTTP_ADDR: "consul-server1:8500"
      CONSUL_HTTP_TOKEN: "e95b599e-166e-7d80-08ad-aee76e7ddf19"
    cap_add:
      - IPC_LOCK
    volumes:
      - /home/sinless777/services/helix/vault/policies:/vault/policies
      - /home/sinless777/services/helix/vault/vault.hcl:/etc/vault.hcl
      - /home/sinless777/services/helix/vault/data:/mnt/vault/data
    command: "server -config=/etc/vault.hcl"
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:8200 || exit 1
      interval: 10s
      retries: 12
      start_period: 10s
      timeout: 10s

  vdb:
    image: mysql:8.4
    volumes:
      - /home/sinless777/services/mysql/vdb:/var/lib/mysql
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    environment:
      MYSQL_ROOT_PASSWORD: Shellshocker93!
      MYSQL_DATABASE: vault
      MYSQL_USER: vault
      MYSQL_PASSWORD: vault


