version: "3.9"

################
##  Networks  ##
################
networks:
  home-net:
    name: home-net
    driver: bridge

  weave-net:
    name: weave-net
    driver: bridge

  proxy-net:
    name: proxy-net
    driver: bridge

###############
##  Volumes  ##
###############

volumes:
  portainer_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/portainer
      o: bind

services:
  portainer:
    image: portainer/portainer-ee:latest
    container_name: portainer
    command: --admin-password 'CGg}#3rUWa-@QvBypyUEE5Mzn-@U=bfGRCPR1Y%p'
    networks:
      - weave-net
      - proxy-net
      - home-net
    volumes:
      - portainer_data:/data
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8000:8000
      - 9000:9000
      - 9443:9443
    restart: unless-stopped
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=America/Denver
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      labels:
        - portainer_service
      mode: replicated
      replicas: 1
      placement:
        constraints: [ node.role == manager, node.labels.cicdBuildsOnly != true ]
      update_config:
        parallelism: 1
      restart_policy:
        condition: any

  agent:
    image: portainer/agent
    environment:
      # REQUIRED: Should be equal to the service name prefixed by "tasks." when
      # deployed inside an overlay network
      AGENT_CLUSTER_ADDR: tasks.agent
      # AGENT_PORT: 9001
      # LOG_LEVEL: debug
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    networks:
      - weave-net
      - proxy-net
      - home-net
    labels:
      com.centurylinklabs.watchtower.enable: true
    deploy:
      mode: global
      placement:
        constraints: [ node.platform.os == linux ]

  ###################
  ##   WEAVE_NET   ##
  ###################

  ###   WATCHTOWER   ###
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: always
    networks:
      - weave-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /etc/timezone:/etc/timezone:ro
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_LABEL_ENABLE=true
      - WATCHTOWER_INCLUDE_RESTARTING=true
      - WATCHTOWER_SCHEDULE=0 0 6 * * *
    labels:
      com.centurylinklabs.watchtower.enable: true

  ###   WEAVESCOPE   ###
  weavescope:
    image: weaveworks/scope:latest
    container_name: weavescope
    hostname: weavescope
    pid: "host"
    privileged: true
    restart: always
    networks:
      - weave-net
    ports:
      - "4040:4040"
    labels:
      works.weave.role: system
      com.centurylinklabs.watchtower.enable: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker=true"
      - "--weave=false"

