version: "3.9"

################
##  Networks  ##
################
networks:
  home-net:
    external: true
    driver: overlay

  weave-net:
    external: true
    driver: overlay

  proxy-net:
    name: proxy-net
    driver: overlay

###############
##  Volumes  ##
###############
volumes:
  unifi:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/unifi
      o: bind

  mysql_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/mysql/nginx-proxy
      o: bind

  nginx_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/nginx-proxy
      o: bind

  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/postgres/maas
      o: bind

  letsencrypt:
    driver: local
    driver_opts:
      type: none
      device: /home/sinless777/services/letsencrypt
      o: bind

services:
  wireguard:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Denver
      - SERVERURL=auto
      - SERVERPORT=51820
      - PEERS=1
      - PEERDNS=auto
      - INTERNAL_SUBNET=10.13.13.0
      - ALLOWEDIPS=0.0.0.0/0
      - LOG_CONFS=true
    volumes:
      - /home/sinless777/services/wireguard/config:/config
      - /lib/modules:/lib/modules
    ports:
      - 51820:51820/udp
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      healthcheck:
        test: ["CMD", "pgrep", "wireguard"]
        interval: 30s
        timeout: 10s
        retries: 3

  proxy:
    image: jc21/nginx-proxy-manager:latest
    networks:
      - home-net
      - proxy-net
      - weave-net
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
      - '21:21'
    environment:
      DB_MYSQL_HOST: "db"
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: ${MYSQL_USER}
      DB_MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      DB_MYSQL_NAME: ${MYSQL_DATABASE}
    volumes:
      - nginx_data:/data
      - letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      update_config:
        parallelism: 1
      resources:
        limits:
          cpus: "1.0"
          memory: 1G
      healthcheck:
        test: [ "CMD", "/bin/check-health" ]
        interval: 30s
        timeout: 10s
        retries: 5

  db:
    image: jc21/mariadb-aria:latest
    networks:
      - proxy-net
      - weave-net
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M

  unifi:
    image: linuxserver/unifi-controller
    networks:
      - home-net
      - weave-net
      - proxy-net
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - MEM_LIMIT=4096
      - MEM_STARTUP=1024
    volumes:
      - unifi:/config
    ports:
      - "3478:3478/udp"
      - "10001:10001/udp"
      - "8080:8080"
      - "8443:8443"
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "1.0"
          memory: 2G
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:8443"]
        interval: 30s
        timeout: 10s
        retries: 5

  sinlessgames:
    image: sinless777/sinlessgames-ui:1.0.89
    networks:
      - proxy-net
      - weave-net
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80"]
        interval: 30s
        timeout: 10s
        retries: 5

  mobius:
    image: sinless777/mobius_gateway:latest
    networks:
      - proxy-net
      - weave-net
    deploy:
      mode: replicated
      replicas: 3
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:80"]
        interval: 30s
        timeout: 10s
        retries: 5

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: Maasdb
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: any
      resources:
        limits:
          cpus: "0.5"
          memory: 512M
      healthcheck:
        test: ["CMD", "pg_isready", "-U", "${POSTGRES_USER}"]
        interval: 30s
        timeout: 10s
        retries: 5
