version: "3.8"

secrets:
  ca.crt:
    file: /home/sinless777/services/elastic_stack/secrets/certificate_authority/ca/ca.crt

  elasticsearch.keystore:
    file: /home/sinless777/services/elastic_stack/secrets/elasticsearch.keystore

  elastic-stack-ca.p12:
    file: /home/sinless777/services/elastic_stack/secrets/certificate_authority/elastic-stack-ca.p12

  elasticsearch.key:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/elasticsearch/elasticsearch.key

  elasticsearch.cert:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/elasticsearch/elasticsearch.crt

  kibana.key:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/kibana/kibana.key

  kibana.cert:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/kibana/kibana.crt

  logstash.pkcs8.key:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/logstash/logstash.pkcs8.key

  logstash.key:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/logstash/logstash.key

  logstash.p12:
    file: /home/sinless777/services/elastic_stack/secrets/keystores/logstash/logstash.p12

  logstash.cert:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/logstash/logstash.crt

  filebeat.key:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/filebeat/filebeat.key

  filebeat.cert:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/filebeat/filebeat.crt

  metricbeat.key:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/metricbeat/metricbeat.key

  metricbeat.cert:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/metricbeat/metricbeat.crt

  packetbeat.key:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/packetbeat/packetbeat.key

  packetbeat.cert:
    file: /home/sinless777/services/elastic_stack/secrets/certificates/packetbeat/packetbeat.crt

################
##  NETWORKS  ##
################
networks:
  elastic-net:
    driver: bridge

  proxy-net:
    external: true

  weave-net:
    external: true

services:
  elasticsearch:
    container_name: elasticsearch
    hostname: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELK_VERSION}
    restart: unless-stopped
    environment:
      CONFIG_DIR: ${ELASTIC_DIR}/config
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ES_JAVA_OPTS: -Xmx${ELASTICSEARCH_HEAP} -Xms${ELASTICSEARCH_HEAP}
      bootstrap.memory_lock: "true"
      discovery.type: single-node
    volumes:
      - /home/sinless777/services/elastic_stack/elasticsearch/config/elasticsearch.yml:${ELASTIC_DIR}/config/elasticsearch.yml:ro
      - /home/sinless777/services/elastic_stack/elasticsearch/data:/usr/share/elasticsearch/data
    secrets:
      - source: elasticsearch.keystore
        target: ${ELASTIC_DIR}/config/elasticsearch.keystore
      - source: ca.crt
        target: ${ELASTIC_DIR}/config/ca.crt
      - source: elasticsearch.cert
        target: ${ELASTIC_DIR}/config/elasticsearch.crt
      - source: elasticsearch.key
        target: ${ELASTIC_DIR}/config/elasticsearch.key
    expose:
      - 9200
      - 9300
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 200000
        hard: 200000
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    healthcheck:
      test: curl -s https://elasticsearch:9200 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    container_name: kibana
    hostname: kibana
    image: docker.elastic.co/kibana/kibana:${ELK_VERSION}
    restart: unless-stopped
    volumes:
      - /home/sinless777/services/elastic_stack/kibana/config/kibana.yml:${KIBANA_DIR}/config/kibana.yml:ro
      - /home/sinless777/services/elastic_stack/kibana/data:/usr/share/kibana/data
    environment:
      CONFIG_DIR: ${KIBANA_DIR}/config
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      ENCRYPTION_KEY: ${XPACK_ENCRYPTION_KEY}
      KIBANA_URL: ${KIBANA_URL}
    secrets:
      - source: ca.crt
        target: ${KIBANA_DIR}/config/ca.crt
      - source: kibana.cert
        target: ${KIBANA_DIR}/config/kibana.crt
      - source: kibana.key
        target: ${KIBANA_DIR}/config/kibana.key
    ports:
      - "5601:5601"
    networks:
      - elastic-net
      - weave-net
      - proxy-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    depends_on:
      - elasticsearch
    links:
      - elasticsearch
    healthcheck:
      test: curl -s https://kibana:5601 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  logstash:
    container_name: logstash
    hostname: logstash
    image: docker.elastic.co/logstash/logstash:${ELK_VERSION}
    restart: unless-stopped
    volumes:
      - /home/sinless777/services/elastic_stack/logstash/config/logstash.yml:${LOGSTASH_DIR}/config/logstash.yml:ro
      - /home/sinless777/services/elastic_stack/logstash/pipeline/logstash.conf:${LOGSTASH_DIR}/pipeline/logstash.conf:ro
      - /home/sinless777/services/elastic_stack/logstash/pipeline/metricbeat.conf:${LOGSTASH_DIR}/pipeline/metricbeat.conf
    environment:
      CONFIG_DIR: ${LOGSTASH_DIR}/config
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LS_JAVA_OPTS: "-Xmx${LOGSTASH_HEAP} -Xms${LOGSTASH_HEAP}"
    secrets:
      - source: ca.crt
        target: ${LOGSTASH_DIR}/config/ca.crt
      - source: logstash.cert
        target: ${LOGSTASH_DIR}/config/logstash.crt
      - source: logstash.key
        target: ${LOGSTASH_DIR}/config/logstash.key
      - source: logstash.pkcs8.key
        target: ${LOGSTASH_DIR}/config/logstash.pkcs8.key
      - source: logstash.p12
        target: ${LOGSTASH_DIR}/config/logstash.p12
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    expose:
      - 12201/udp
      - 5044
      - 9600
      - 5000/tcp
      - 5000/udp
    depends_on:
      - elasticsearch
      - kibana
    links:
      - elasticsearch
      - kibana
    healthcheck:
      test: curl -s https://logstash:9600 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5

  fleet-server:
    container_name: elastic-agent
    hostname: elastic-agent
    image: docker.elastic.co/beats/elastic-agent:${ELK_VERSION}
    restart: unless-stopped
    environment:
      ## Fleet
      FLEET_SERVER_ENABLE: "1"
      FLEET_SERVER_POLICY_ID: "fleet-server-apm"
      FLEET_SERVER_ELASTICSEARCH_HOST: http://elasticsearch:9200
      FLEET_SERVER_ELASTICSEARCH_USERNAME: "${ELASTIC_USERNAME}"
      FLEET_SERVER_ELASTICSEARCH_PASSWORD: "${ELASTIC_PASSWORD}"
      FLEET_SERVER_CERT: /etc/pki/tls/certs/fleet-server.pem
      FLEET_SERVER_CERT_KEY: /etc/pki/tls/private/fleet-server-key.pem
      FLEET_CA: '/ca.crt'
      ELK_VERSION: ${ELK_VERSION}
      FLEET_URL: https://fleet-server:8220
      KIBANA_HOST: "https://kibana:5601"
      KIBANA_FLEET_USERNAME: "${ELASTIC_USERNAME}"
      KIBANA_FLEET_PASSWORD: "${ELASTIC_PASSWORD}"
      PREFLIGHT_CHECK: 1
    secrets:
      - source: ca.crt
        target: /ca.crt
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    ports:
      - "2222:22"
    depends_on:
      elasticsearch: { condition: service_healthy }
      kibana: { condition: service_healthy }
    links:
      - elasticsearch
      - kibana
    healthcheck:
      test: [ "CMD-SHELL", "curl -s -k https://localhost:8220/api/status | grep -q 'HEALTHY'" ]
      retries: 300
      interval: 1s

  ###   BEATS   ###

  packetbeat:
    container_name: packetbeat
    hostname: packetbeat
    user: root
    image: docker.elastic.co/beats/packetbeat:${ELK_VERSION}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: packetbeat -e -strict.perms=false
    volumes:
      - /home/sinless777/services/elastic_stack/packetbeat/config/packetbeat.yml:${PACKETBEAT_DIR}/packetbeat.yml:ro
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONFIG_DIR: ${PACKETBEAT_DIR}/config
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LS_JAVA_OPTS: "-Xmx${PACKETBEAT_HEAP} -Xms${PACKETBEAT_HEAP}"
    secrets:
      - source: ca.crt
        target: ${PACKETBEAT_DIR}/config/ca.crt
      - source: packetbeat.cert
        target: ${PACKETBEAT_DIR}/config/packetbeat.crt
      - source: packetbeat.key
        target: ${PACKETBEAT_DIR}/config/packetbeat.key
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    depends_on:
      - logstash
    links:
      - logstash

  metricbeat:
    container_name: metricbeat
    hostname: metricbeat
    user: root
    image: docker.elastic.co/beats/metricbeat:${ELK_VERSION}
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - NET_RAW
    command: "/bin/bash -c while true; do metricbeat -e; sleep 1; done"
    volumes:
      - /home/sinless777/services/elastic_stack/metricbeat/config/metricbeat.yml:${METRICBEAT_DIR}/metricbeat.yml
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      CONFIG_DIR: ${METRICBEAT_DIR}/config
      ELASTIC_USERNAME: ${ELASTIC_USERNAME}
      ELASTIC_PASSWORD: ${ELASTIC_PASSWORD}
      LS_JAVA_OPTS: "-Xmx${METRICBEAT_HEAP} -Xms${METRICBEAT_HEAP}"
    secrets:
      - source: elastic-stack-ca.p12
        target: /etc/pki/ca-trust/source/anchors/elastic-stack-ca.p12
      - source: ca.crt
        target: /etc/pki/ca-trust/source/anchors/ca.crt
      - source: metricbeat.cert
        target: ${METRICBEAT_DIR}/config/metricbeat.crt
      - source: metricbeat.key
        target: ${METRICBEAT_DIR}/config/metricbeat.key
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    depends_on:
      - logstash
      - elasticsearch
      - fleet-server
    links:
      - logstash

  filebeat:
    container_name: filebeat
    hostname: filebeat
    image: docker.elastic.co/beats/filebeat:${ELK_VERSION}
    restart: unless-stopped
    command: filebeat -e -strict.perms=false
    volumes:
      - /home/sinless777/services/elastic_stack/filebeat/config/filebeat.yml:${FILEBEAT_DIR}/filebeat.yml:ro
    environment:
      CONFIG_DIR: ${FILEBEAT_DIR}/config
      LS_JAVA_OPTS: "-Xmx${FILEBEAT_HEAP} -Xms${FILEBEAT_HEAP}"
    secrets:
      - source: ca.crt
        target: ${FILEBEAT_DIR}/config/ca.crt
      - source: filebeat.cert
        target: ${FILEBEAT_DIR}/config/filebeat.crt
      - source: filebeat.key
        target: ${FILEBEAT_DIR}/config/filebeat.key
    expose:
      - 9000
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    depends_on:
      - logstash
    links:
      - logstash
