version: "3.8"

secrets:
  ca.crt:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificate_authority/ca/ca.crt

  fleet-server.cert:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/fleet-server/fleet-server.crt

  fleet-server.key:
    file: ${SECRETS_DIR}/elastic_stack/secrets/certificates/fleet-server/fleet-server.key

################
##  NETWORKS  ##
################
networks:
  elastic-net:
    external: true

  proxy-net:
    external: true

  weave-net:
    external: true

services:
  elastic-agent:
    image: docker.elastic.co/beats/elastic-agent:8.9.0
    container_name: elastic-agent
    restart: always
    user: root # note, synthetic browser monitors require this set to `elastic-agent`
    environment:
      ##
      ## Common Variables
      ##
      #
      # (string) The Elasticsearch host to communicate with.
      #
      # Default: http://elasticsearch:9200
      ELASTICSEARCH_HOST: https://192.168.86.140:9200
      # (string) The basic authentication username used to connect to Kibana and retrieve a
      # service_token for Fleet.
      #
      # Default: elastic
      ELASTICSEARCH_USERNAME: ${ELASTIC_USERNAME}
      # (string) The basic authentication password used to connect to Kibana and retrieve a
      # service_token for Fleet.
      #
      # Default: changeme
      ELASTICSEARCH_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      # (string) The path to a certificate authority.
      #
      # By default, Elastic Agent uses the list of trusted certificate authorities (CA) from the
      # operating system where it is running. If the certificate authority that signed your node
      # certificates is not in the host system’s trusted certificate authorities list, use this
      # config to add the path to the .pem file that contains your CA’s certificate.
      #
      # Default: ""
      ELASTICSEARCH_CA: ${FLEET_DIR}/config/ca.crt
      # (string) The Kibana host.
      #
      # Default: http://kibana:5601
      KIBANA_HOST: https://192.168.86.140:5601
      # (string) The basic authentication username used to connect to Kibana to retrieve
      # a service_token.
      #
      # Default: elastic
      KIBANA_USERNAME: ${ELASTIC_USERNAME}
      # (string) The basic authentication password used to connect to Kibana to retrieve
      # a service_token.
      #
      # Default: changeme
      KIBANA_PASSWORD: ${ELASTICSEARCH_PASSWORD}
      # (string) The path to a certificate authority.
      #
      # By default, Elastic Agent uses the list of trusted certificate authorities (CA) from the
      # operating system where it is running. If the certificate authority that signed your
      # node certificates is not in the host system’s trusted certificate authorities list, use
      # this config to add the path to the .pem file that contains your CA’s certificate.
      #
      # Default: ""
      KIBANA_CA: ${FLEET_DIR}/config/ca.crt
      ##
      ## Prepare Kibana for Fleet
      ##
      #
      # (int) Set to 1 to enable Fleet setup. Enabling Fleet is required before Fleet Server
      # will start. When this action is not performed, a user must manually log in to Kibana
      # and visit the Fleet page to enable setup.
      #
      # Default: none
      KIBANA_FLEET_SETUP: 1
      # (string) The Kibana host to enable Fleet on. Overrides FLEET_HOST when set.
      #
      # Default: http://kibana:5601
      KIBANA_FLEET_HOST: https://192.168.86.140:5601
      ##
      ## Prepare Kibana for Fleet
      ##
      #
      # (int) Set to 1 to bootstrap Fleet Server on this Elastic Agent. When set to 1, this
      # automatically forces Fleet enrollment as well.
      #
      # Default: none
      FLEET_SERVER_ENABLE: 1
      # (string) The name of the policy for Fleet Server to use on itself. Overrides
      # FLEET_TOKEN_POLICY_NAME when set.
      #
      # Default: none
      FLEET_SERVER_POLICY_NAME: fleet-server
      #
      # (string) Service token to use for communication with Elasticsearch and Kibana if
      # KIBANA_FLEET_SETUP is enabled. If the service token value and service token path are
      # specified the value may be used for setup and the path is passed to the agent in
      # the container.
      #
      # Default: none
      FLEET_SERVER_SERVICE_TOKEN: "AAEAAWVsYXN0aWMvZmxlZXQtc2VydmVyL3Rva2VuLTE2OTA2NjgxMjI5NDQ6RkZZWjBiNDVRZWlQcU91LU9ETGdLUQ"
      # (bool) Set to 1 to enroll the Elastic Agent into Fleet Server.
      #
      # Default: false
      FLEET_ENROLL: 1
    secrets:
      - source: ca.crt
        target: ${FLEET_DIR}/config/ca.crt
      - source: fleet-server.cert
        target: ${FLEET_DIR}/config/fleet-server.cert
      - source: fleet-server.key
        target: ${FLEET_DIR}/config/fleet-server.key
    networks:
      - elastic-net
      - weave-net
    labels:
      com.centurylinklabs.watchtower.enable: "true"
    ports:
      - 8220:8220
    healthcheck:
      test: curl -s https://elastic-agent:8220 >/dev/null; if [[ $$? == 52 ]]; then echo 0; else echo 1; fi
      interval: 30s
      timeout: 10s
      retries: 5