setup.dashboards.enabled: true

# Forcing Elasticsearch index template 
setup.template.overwrite: true

setup.kibana.host: "kibana:5601"
setup.kibana.protocol: "https"
setup.kibana.ssl.enabled: true
setup.kibana.username: 'Sinless777'
setup.kibana.password: 'M!9EZj=JENhky9^Q!dVd?A]H]Z+mXCu4Fk]t,Luu'
setup.kibana.ssl.certificate_authorities: ["/etc/pki/ca-trust/source/anchors/ca.crt"]
setup.kibana.ssl.certificate: /usr/share/metricbeat/metricbeat.crt
setup.kibana.ssl.key: /usr/share/metricbeat/metricbeat.key
setup.kibana.ssl.verification_mode: "none"

metricbeat.autodiscover:
  providers:
    - type: docker
      hints.enabled: true

metricbeat.modules:
- module: docker
  metricsets:
    - "container"
    - "cpu"
    - "diskio"
    - "healthcheck"
    - "info"
    - "image"
    - "memory"
    - "network"
  hosts: ["unix:///var/run/docker.sock"]
  period: 10s
  enabled: true


processors:
  - add_cloud_metadata: ~

output.logstash:
  hosts: ["logstash:5044"]
  ssl.certificate_authorities: ["/etc/pki/ca-trust/source/anchors/ca.crt"]
  ssl.certificate: /usr/share/metricbeat/metricbeat.crt
  ssl.key: /usr/share/metricbeat/metricbeat.key
  index: metricbeat
