---
server.name: kibana
server.host: 0.0.0.0
server.publicBaseUrl: "kibana.sinlessgamesllc.com"

# Elasticsearch settings
elasticsearch.hosts: [ "https://elasticsearch:9200" ]
elasticsearch.ssl.certificateAuthorities: [ "/usr/share/kibana/ca.crt" ]
elasticsearch.username: "Sinless777"
elasticsearch.password: "M!9EZj=JENhky9^Q!dVd?A]H]Z+mXCu4Fk]t,Luu"

# Elasticsearch monitoring settings
monitoring.ui.container.elasticsearch.enabled: true

# X-Pack Security
xpack.security.enabled: true
xpack.encryptedSavedObjects.encryptionKey: "R!ZYhi^DKuFauQR8TRz4^r?x%qQin}*+,eBc_dP=n}2+gc~PuT>p]HMP>3?w6:!6sdCw2Jh=8YKAtcQZwfVULdFn95_3odyVGuUw"
xpack.security.encryptionKey: "R!ZYhi^DKuFauQR8TRz4^r?x%qQin}*+,eBc_dP=n}2+gc~PuT>p]HMP>3?w6:!6sdCw2Jh=8YKAtcQZwfVULdFn95_3odyVGuUw"
xpack.reporting.encryptionKey: "R!ZYhi^DKuFauQR8TRz4^r?x%qQin}*+,eBc_dP=n}2+gc~PuT>p]HMP>3?w6:!6sdCw2Jh=8YKAtcQZwfVULdFn95_3odyVGuUw"

# SSL settings

server.ssl.enabled: true
server.ssl.certificate: "/usr/share/kibana/kibana.crt"
server.ssl.key: "/usr/share/kibana/kibana.key"
server.ssl.certificateAuthorities: [ "/usr/share/kibana/ca.crt" ]

# fleet settings for Elastic-agent
xpack.fleet.enabled: true
xpack.fleet.agents.enabled: true
xpack.fleet.agents.tlsCheckDisabled: true
xpack.fleet.agents.kibana.host: "https://kibana:5601"
xpack.fleet.agents.elasticsearch.host: "https://elasticsearch:9200"
