name: Update Docker Compose

on:
  repository_dispatch:
    types: [new-docker-image]

jobs:
  update-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get the event payload
        id: get-payload
        run: echo "${{ github.event.client_payload.tag }}" > .tag

      - name: Read the current sinlessgames image tag from docker-compose.home.yml
        id: read_compose_tag
        run: |
          current_image=$(grep 'image: sinless777/sinlessgames-ui' docker-compose.home.yml | awk -F: '{print $3}')
          echo "CURRENT_IMAGE_TAG=${current_image}" >> $GITHUB_ENV
  
      - name: Compare tags and update docker-compose.home.yaml if necessary
        run: |
          if [ "$CURRENT_IMAGE_TAG" != "$TAG" ]; then
            echo "Updating docker-compose.home.yaml with new tag: $TAG"
            sed -i "s|services.sinlessgames.image: sinless777/sinlessgames-ui:${CURRENT_IMAGE_TAG}|services.sinlessgames.image: sinless777/sinlessgames-ui:${TAG}|" docker-compose.home.yml
          else
            echo "No update needed. Current tag ($CURRENT_IMAGE_TAG) matches the desired tag ($TAG)."
          fi
          
      - name: Commit changes
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
        run: |
          if [ "$CURRENT_IMAGE_TAG" != "$TAG" ]; then
            git config --global user.email "disdainful777@gmail.com"
            git config --global user.name "Sinless777"
            git pull origin
            git add docker-compose.home.yml
            git commit -m "Update sinlessgames image tag to ${TAG}"
            git push origin
          fi
