name: Update Docker Compose

on:
  repository_dispatch:
    types: [new-docker-image]

jobs:
  update-docker-compose:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4
        with:
          ref: 'refs/heads/main' # Replace 'main' with your default branch name

      - name: Get the event payload
        id: get-payload
        run: echo "${{ github.event.client_payload.tag }}" > .tag

      - name: Update Docker Compose file
        run: |
          TAG=$(cat .tag)
          sed -i "s|image: sinless777/sinlessgames-ui:.*|image: sinless777/sinlessgames-ui:${TAG}|g" docker-compose.home.yml

      - name: Commit changes
        run: |
          git config --global user.email "disdainful777@gmail.com"
            git config --global user.name "Sinless777"
            git pull origin
            git add dovker-compose.home.yaml
            git commit -m "update docker compose"
            git push origin
